services:
  # Backend (Node.js)
  backend:
    build:
      context: ./backend  # Contexte de construction pour le backend
      dockerfile: Dockerfile  # Utilisation du Dockerfile dans le dossier backend
    ports:
      - "3000:3000"  # Mappe le port 5000 du conteneur au port 5000 de l'hôte
    depends_on:
      - db  # Assure que la base de données MongoDB est prête avant de démarrer le backend
    networks:
      - app-network

# MongoDB
  db:
    image: mongo:latest  # Utilisation de l'image officielle MongoDB
    ports:
      - "27017:27017"  # Mappe le port 27017 du conteneur au port 27017 de l'hôte
    volumes:
      - ./mongo/data:/data/db  # Persiste les données dans un répertoire local
    networks:
      - app-network

# Définition du réseau interne pour la communication entre les services
networks:
  app-network:
    driver: bridge