# Étape 1 : Construire l'application Vue.js
FROM node:16

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json (ou yarn.lock)
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code source
COPY . .

# Exposer le port 5173 pour Vite (mode dev)
EXPOSE 5173

# Démarrer l'application Vue.js en mode développement (via Vite)
CMD [ "npm", "run", "dev" ]
