# Utiliser une image Node pour le backend
FROM node:18

# Définir le dossier de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY package.json ./package.json

# Installer les dépendances
RUN npm install

# Copier les fichiers de l'application backend
COPY . .

# Récupérer les fichiers dist du frontend depuis l'image sur Docker Hub
COPY --from=evinp/frontend:latest /dist ./dist

# Démarrer l'application backend
CMD ["npm", "start"]
