# Utiliser l'image officielle MongoDB
FROM mongo:latest

# Exposer le port par défaut de MongoDB
EXPOSE 27017

# Volume pour persister les données
VOLUME /data/db

# Commande par défaut (MongoDB démarre automatiquement avec cette image)
CMD ["mongod"]
